### ISSUE TITLE
go-pos のテストを加える

### ISSUE THREAD

**Issue by k-okada** [start-jsk/rtmros_common#554]
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/test/test-samplerobot.py
ですが，いまはload patternなので，go-pos 版も加えてくください．

```
    def test_go_pos(self):
```
という関数をついかすればいいです．

Cc: @terasawa

**Comment by snozawa** [comment]
https://github.com/start-jsk/rtmros_common/pull/800
でeuslisp経由でgo-posテストをするようになりました。
