### ISSUE TITLE
Adding euslisp documentation page

### ISSUE THREAD

**Issue by snozawa** [start-jsk/rtmros_common#601]
I'd like to add Euslisp documentation page for rtmros_common (especially for rtm-ros-robot-interface.l). 

Currently, some of euslisp documentation is generated from ``documatation.l``[1] 
and generated documentation is located in github.io pages and gh-pages branch[2].

[1] https://github.com/euslisp/jskeus/
[2] http://euslisp.github.io/jskeus/

For rtmros_common, can I create github.io and gh-pages branch as ``jskeus`` repository for Euslisp documentation?

We can generate Euslisp documentation in this PR:
https://github.com/start-jsk/rtmros_common/pull/597
``roscd hrpsys_ros_bridge/doc && make``

**Comment by snozawa** [comment]
こちらいかがでしょうか。
新しくrtmrosのシステムをさわる人員が増えて必要になっています。

euslisp -> markdownのプログラムのほうが良いという話になっていたのですが、なぜでしたでしょうか。

**Comment by k-okada** [comment]
platexシステムはeus/jskeusで使っているからしょうがないけど，markdownにしたときに
platex -> html2markdown
と新しいツールを導入するよりは，今のものを拡張していった
documentation.l
の方が保守性が高いでしょう．という話です．

ただ，euslisp/jskのように変更有る度に自分のリポジトリにコミットしていると，
無駄にヒストリがたまってどんどん重くなっていってしまうので，考えものですね．
チョット考えます．


--
◉ Kei Okada


2015-04-22 20:58 GMT+09:00 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
> platexシステムはeus/jskeusで使っているからしょうがないけど，markdownにしたときに platex -> html2markdown と新しいツールを導入するよりは，今のものを拡張していった documentation.l の方が保守性が高いでしょう．という話です． 

なるほど，わかりました．

>  ただ，euslisp/jskのように変更有る度に自分のリポジトリにコミットしていると， 無駄にヒストリがたまってどんどん重くなっていってしまうので，考えものですね． チョット考えます．

そうですね．
コードに履歴が残ってくれてるので，ドキュメント自体は履歴なしが重くならなくてよさそうですね．

**Comment by k-okada** [comment]
えらく時間かかってしまいましたが，
- http://euslisp-docs.readthedocs.org/en/latest/

みたいな感じでやっていこうかと思っています．
https://github.com/jsk-ros-pkg/jsk_roseus/commit/9c7ed34dd0b6d6e1d7e714911748fd292257a36f
みたいな感じで作っておくと，
https://github.com/jsk-ros-pkg/euslisp-docs/tree/master/docs/roseus
のindex.md以外(API References)は自動でできたAPIです．あとはいい感じのindex.mdを手動でつくって，
さらに表紙の
https://github.com/jsk-ros-pkg/euslisp-docs/blob/master/docs/index.md
は手書きです．

もんだいなさそうなら，pr2eus, rtmros_common あたりまで順次対応していきたいと思います．

ただ，いまおもうと，やっぱ各リポジトリに別のブランチを作ってそこにドキュメントを入れるのでも
いいかな，とおもったりもするんだけど，そうするとやっぱ.git以下が重くなったりするのかな．

**Comment by k-okada** [comment]
http://euslisp-docs.readthedocs.org/en/latest/

にpr2eus, hrpsys_ros_bridgeを追加しました．
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/134
https://github.com/start-jsk/rtmros_common/pull/722
が通れば自動で動くはずです．roseusのshadowfixまち．今回は数日更新ないです．
どうもjadeの新しいのを入れているらしく，geneusが原因？とおもうと何もいえないか．
