### ISSUE TITLE
rtmlaunch location changed?

### ISSUE THREAD

**Issue by RyuYamamoto** [start-jsk/rtmros_common#735]
```alias rtmlaunch='`rospack find hrpsys_ros_bridge`/scripts/rtmlaunch'```

.bashrcに上記を書き込んでこれまで使えていたのですが,最近以下のエラーが出るようになりました.起動方法は変わったでしょうか?

```bash: /opt/ros/hydro/share/hrpsys_ros_bridge/scripts/rtmlaunch: そのようなファイルやディレクトリはありません```

dpkg -p ros-hydro-hrpsys-tools | grep Ver
Version: 1.2.12-0precise-20150507-0216-+0000

**Comment by eisoku9618** [comment]
aliasを貼らなくても自動的にsetup.bashから読まれるようになりましたので，その設定はいらないくなったと思います．

**Comment by RyuYamamoto** [comment]
了解致しました.

ありがとうございます．
