### ISSUE TITLE
EmergencyStopperの状態をeusで取得したい

### ISSUE THREAD

**Issue by mmurooka** [start-jsk/rtmros_common#770]
@snozawaさん
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/src/HrpsysSeqStateROSBridge.cpp#L791-L797
でpublishされているemergency_stopperの状態を
eusで受け取りたいのですが，
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L1109-L1123
の下にこのトピックをsubscribeするメソッドを追加してもよろしいでしょうか．

**Comment by mmurooka** [comment]
cc: @YutaKojio

**Comment by k-okada** [comment]
もうそろそろopenrtmのポートを指定したら自動で読み込んでrosでpublishするプログラムができるといいですね．

--
◉ Kei Okada

**Comment by mmurooka** [comment]
大変そうですが，そう思います．
もしやるとしたらポートに関する何かしらをIDLに書くようにするところから始めないといけない（というので合っていますか）


2015年7月15日 17:09 Kei Okada <notifications@github.com>:

> もうそろそろopenrtmのポートを指定したら自動で読み込んでrosでpublishするプログラムができるといいですね．
>
> --
> ◉ Kei Okada
>
>
> On Wed, Jul 15, 2015 at 4:56 PM, Masaki Murooka <notifications@github.com>
>
> wrote:
>
> > cc: @YutaKojio <https://github.com/YutaKojio>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/start-jsk/rtmros_common/issues/770#issuecomment-121521547>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/rtmros_common/issues/770#issuecomment-121523997>
> .
>



-- 
室岡雅樹（Masaki Murooka）
masaki.murooka@gmail.com

**Comment by k-okada** [comment]
port名とその型を引数にして動くプログラムができると思います．，で，できるかな．

--
◉ Kei Okada


2015-07-15 18:27 GMT+09:00 Masaki Murooka <notifications@github.com>:

**Comment by snozawa** [comment]
@mmurooka 
ポートをだすものをつくる場合は、@k-okadaさんのおっしゃるやり方がよいです。
IDLのように静的なファイルにかいてあるものだけでなく、例えばセンサのポートは
ModelLoaderのセンサ情報に基づいて動的につけたりしてるので、そういうのにも対応がいります。
ちなみに、
```
hcf.kf("acc")
hcf.kf("acc").get_port_profile()
hcf.kf("acc").get_port_profile().properties
```
みたいなのでポート情報が動的にえられます。

**Comment by snozawa** [comment]
https://github.com/start-jsk/rtmros_common/issues/770#issue-95129274
は、roseusでsubscribeする場合は
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L13
このへんでコールバックをつくっています。

話がそれますが、メソッドの追加は、
`getEmergencyStopperParam`、
`setEmergencyStopperParam`
対応のめそっどがなかったので、追加してもらえるとたすかります。

https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L1094
のように追加したら、メソッドが追加されます。

**Comment by k-okada** [comment]
引数ににしたプログラムにするのは静的動的かかわらず，指定したものを処理する，というスタイルですね．
でプログラムとしては限りなくopenrtmレイヤで書けるものになるかと思います．pythonで書いておいて，
必要だったらモジュールでインポートしてhcfかなにかから動的に，という感じだと負います．


--
◉ Kei Okada


2015-07-15 20:00 GMT+09:00 Shunichi Nozawa <notifications@github.com>:

**Comment by snozawa** [comment]
@mmurooka さん
これOK？

**Comment by mmurooka** [comment]
はい，https://github.com/start-jsk/rtmros_common/pull/772でOKになりましたので，closeします．

> もうそろそろopenrtmのポートを指定したら自動で読み込んでrosでpublishするプログラムができるといいですね．

は，別でIssue立てます．
