### ISSUE TITLE
Range/Image/PointCloudをrtmからROSに変換するプログラム

### ISSUE THREAD

**Issue by YoheiKakiuchi** [start-jsk/rtmros_common#784]
ImageSensorROSBridgeのようなImageをROS形式に変換するプログラムと同等な、Range、PointCloudへ変換するプログラムはどこかにありますでしょうか？
なければ、hrpsys_ros_bridgeに作ろうと思います。
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/src/ImageSensorROSBridge.cpp

**Comment by k-okada** [comment]
はいいいともいます．

--
◉ Kei Okada


2015-08-10 12:19 GMT+09:00 Yohei Kakiuchi <notifications@github.com>:

**Comment by YoheiKakiuchi** [comment]
added by https://github.com/start-jsk/rtmros_common/pull/785
