### ISSUE TITLE
3rd test takes too much time exceeding 50 minutes

### ISSUE THREAD

**Issue by garaemon** [start-jsk/rtmros_common#813]
https://github.com/start-jsk/rtmros_common/blob/master/.travis.yml#L23
https://travis-ci.org/start-jsk/rtmros_common/jobs/78539507

Can we remove it?

It compiles openhrp3 and hrpsys

**Comment by garaemon** [comment]
cc: @orikuma

**Comment by garaemon** [comment]
Or use jenkins?

**Comment by garaemon** [comment]
* https://github.com/start-jsk/rtmros_common/pull/812
* https://github.com/start-jsk/rtmros_common/pull/811
* https://github.com/start-jsk/rtmros_common/pull/804

These  3 PRs failed to compile the 3rd test.

But I think this test is important, with lthe atest openhrp3 and hrpsys.

**Comment by garaemon** [comment]
It specifies NOT_TEST_INSTALL="true" but it looks it runs https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L172

**Comment by garaemon** [comment]
> It specifies NOT_TEST_INSTALL="true" but it looks it runs https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L172

it's not correct. The test ends during run_tests.

**Comment by garaemon** [comment]
It may be slow because of `ROS_PARALLEL_JOBS="-j1 -l1"`

**Comment by snozawa** [comment]
Third test is for euslisp test.
For euslisp test, I used dependent software from source.

However, we just need to use hrpsys-base from source, but openhrp3 can be deb.

**Comment by snozawa** [comment]
https://github.com/start-jsk/rtmros_common/pull/806

**Comment by snozawa** [comment]
If this problem occurs again, please reopen this issue.
