### ISSUE TITLE
HrpsysSeqStateROSBridgeの出すodomのchild_frame_idについて

### ISSUE THREAD

**Issue by orikuma** [start-jsk/rtmros_common#825]
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/src/HrpsysSeqStateROSBridge.cpp#L558

**Comment by orikuma** [comment]
ここはなぜコメントアウトされているのでしょうか?
Odometryのchild_frame_idはtwistの座標系を指定するらしいので, これがないと座標変換時に困る気がします.

**Comment by garaemon** [comment]
odomじゃなくてroot linkにしてPR送ってください

**Comment by orikuma** [comment]
http://docs.ros.org/api/nav_msgs/html/msg/Odometry.html
によるとtwistはchiild_frame_id座標系表現にする必要があるとのことなので, root_linkにする場合twistの座標系が変わりますが大丈夫でしょうか.
それで良ければ修正します.

**Comment by garaemon** [comment]
PR2のものを確認してください

**Comment by orikuma** [comment]
PR2のchild_frame_idは''でしたが, twistは動かしてみた限りではbase_link座標系表現のようでした.

**Comment by orikuma** [comment]
修正したのでcloseします.
