### ISSUE TITLE
hrpsys-simulatorでnan/infがfoundと出る

### ISSUE THREAD

**Issue by YuOhara** [start-jsk/rtmros_common#906]
rtmlaunch hrpsys_ros_bridge_tutorials samplerobot.launch
して別ターミナルで、
(progn (load "package://hrpsys_ros_bridge_tutorials/euslisp/samplerobot-interface.l") (samplerobot-init) (send *ri* :angle-vector (send *sr* :reset-pose)) (send *ri* :wait-interpolation) (send *ri* :start-auto-balancer))
とすると
```
[abc,JointPathEx] ERROR nan/inf is found
```
とエラーが出て、そこからstを入れるシミュレータが落ちます（リスタートします）。

同じ理由で、choreonoidも最新のコードで落ちているように見えます。

ターミナルのログは以下です(hrpsys-simulator)
https://gist.github.com/YuOhara/b54ae20bae14ce222a43

**Comment by snozawa** [comment]
hrpsys_ros_bridge_tutorials -> hrpsys_ros_bridgeにしてみて、
```
rtmlaunch hrpsys_ros_bridge samplerobot.launch USE_UNSTABLE_RTC:=true

(progn (load "package://hrpsys_ros_bridge/euslisp/samplerobot-interface.l") (samplerobot-init) (send *ri* :angle-vector (send *sr* :reset-pose)) (send *ri* :wait-interpolation) (send *ri* :start-auto-balancer))
```
ではどうでしょうか。

**Comment by snozawa** [comment]
```
rtmlaunch hrpsys samplerobot.launch

python -i `rospack find hrpsys`/samples/SampleRobot/samplerobot_auto_balancer.py
```
の結果も教えてください。

**Comment by snozawa** [comment]
また，
https://github.com/fkanehiro/hrpsys-base/pull/944
を試しにmergeしてみて結果がかわるかも教えてください．

**Comment by YuOhara** [comment]
hrpsys->masterbranch はじめの出力 (rtm launch hrpsys_ros_bridge)
https://gist.github.com/YuOhara/f59e623927581df84b6e
hrpsys->masterbranch 二個目の出力　(rtmlaunch hrpsys)
https://gist.github.com/YuOhara/9b24d10b229fcd719323

**Comment by YuOhara** [comment]
hrpsys->masterbranch はじめの出力 (rtm launch hrpsys_ros_bridge)
https://gist.github.com/YuOhara/48bbeea931917dd900bd
hrpsys->masterbranch 二個目の出力　(rtmlaunch hrpsys)
https://gist.github.com/YuOhara/a6313f2157f2481785d1

**Comment by YuOhara** [comment]
結果は変わってないように見えて、hrpsys_ros_bridgeでabc入れるとエラーが発生してst入れるとsimulatorが落ちます

**Comment by snozawa** [comment]
hrpsys-baseを
5652d17c93861a3ab11746af3c600f1f31dabf18
までもどしてみて，
hrpsys-base, hrpsys_ros_bridgeの両方を
```
catkin bt --start-with-this --force-cmake --cmake-args -DENABLE_DOXYGEN=OFF
```
してみてください．

**Comment by YuOhara** [comment]
hrpsys->(5652d17c93861a3ab11746af3c600f1f31dabf18)branch はじめの出力 (rtm launch hrpsys_ros_bridge)

https://gist.github.com/YuOhara/e11ae8842c04d91d2d34
こちら、エラーなく動いているように見えます。

**Comment by snozawa** [comment]
ところでこれはubuntu 14.04で、まだ解決してないでしょうか？

**Comment by YuOhara** [comment]
14.04です。
解決しているかは、明日確認します

**Comment by YuOhara** [comment]
14.04では解決していなかったです(rtm_launch hrpsys_ros_bridge samplerobot.launchをして、start-abc->start-stでhrpsys_simulatorが落ちました)
12.04マシンが手元にないので、そちらは確認できていないです。

**Comment by snozawa** [comment]
12.04以前はtravis手元実機含め落ちてないですね。

**Comment by snozawa** [comment]
マージされたので確認をお願いします

**Comment by YuOhara** [comment]
hrpsys_simulator, choreonoidともにちゃんとabc, stが入ることを確認しました
