### ISSUE TITLE
Release 1.3.2 (or greater)?

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_common#930]
Last release was [1.3.1 in Dec 2015](https://github.com/start-jsk/rtmros_common/releases/tag/1.3.1).

[Indigo public sync is scheduled this week](http://lists.ros.org/pipermail/ros-release/2016-April/004841.html).

**Comment by k-okada** [comment]
Please help me to crate changelog, maybe create or that update change log may good

--
◉ Kei Okada

2016/04/19 0:02、Isaac I.Y. Saito <notifications@github.com> のメッセージ:

**Comment by 130s** [comment]
Sure

**Comment by 130s** [comment]
Done awhile ago https://github.com/start-jsk/rtmros_common/releases/tag/1.3.2
